version: '3.7'
services:
  server:
    build:
      context: .
      dockerfile: nginx/Dockerfile
    image: node_todo_server
    ports:
      - '80:80' # Connect localhost 80 port to container 80 port
    links: # Link services to access http://app and  http://api inside the container
      - api:api
      - client:client
  client:
    build:
      context: ./client
      dockerfile: Dockerfile
    image: crantodev/node_todo_client
    environment:
      - NODE_ENV=development
      - CI=true
    volumes:
      - ./../client:/usr/src/client
    depends_on:
      - "api"
  api:
    build:
      context: ./api
      dockerfile: Dockerfile
    image: crantodev/node_todo_api
    environment:
      - DB_NAME=node_todo
      - DB_USER=node_todo
      - DB_PASS=node_todo
      - DB_HOST=db
      - DB_DIALECT=mysql
      - DB_PORT=3306
      - NODE_ENV=development
    links:
      - db:db
    volumes:
      - ./../api:/usr/src/api
    depends_on:
      - "db"
  db:
    build:
      context: ./db
      dockerfile: Dockerfile
    image: crantodev/node_todo_db
    environment:
      - MYSQL_DATABASE=node_todo
      - MYSQL_USER=node_todo
      - MYSQL_ROOT_PASSWORD=root
      - MYSQL_PASSWORD=node_todo
    ports:
      - "3306:3306"
    volumes:
      - ~/.data/node_todo:/var/lib/mysql
